name: Test Ambuild Hoomd Blue 2

on:
  workflow_dispatch:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run at 18:00 on Thursdays
    - cron:  '00 18 * * 4'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests with Docker (include Hoomdblue 2)
      run: |
        cd ./tests
        sudo  ./run_tests_docker.sh
